apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pubsub-sub
  namespace: atlas
spec:
  replicas: 1 
  template: 
    metadata:
      labels:
        app: pubsub-sub
    spec: 
      containers:
      - name: pubsub-sub
        image: infobloxcto/atlas.pubsub-sub:c625301-dirty
        imagePullPolicy: Always
        env:
        ports:
          - name: grpc
            containerPort: 8081 
        args: [
            # "-log",
            "debug"
         ]
